// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add_voucher": {
            "get": {
                "description": "add voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voucher"
                ],
                "summary": "add voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "voucher",
                        "name": "voucher",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "node api",
                        "name": "node",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Voucher"
                        }
                    }
                }
            }
        },
        "/add_watch_file": {
            "get": {
                "description": "add watch file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch File"
                ],
                "summary": "add watch file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "watch file path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "index file or index file ext",
                        "name": "index",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.WatchFile"
                        }
                    }
                }
            }
        },
        "/reference": {
            "get": {
                "description": "upload file reference",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload File"
                ],
                "summary": "upload file reference",
                "parameters": [
                    {
                        "type": "string",
                        "description": "file path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "usable",
                        "name": "usable",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/remove_voucher": {
            "get": {
                "description": "remove voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voucher"
                ],
                "summary": "remove voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "voucher",
                        "name": "voucher",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "affect rows",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/remove_watch_file": {
            "get": {
                "description": "remove watch file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch File"
                ],
                "summary": "remove watch file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "watch file path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "affect rows",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/upload_files": {
            "get": {
                "description": "pagination list upload files",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload File"
                ],
                "summary": "list upload files",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UploadFile"
                        }
                    }
                }
            }
        },
        "/vouchers": {
            "get": {
                "description": "pagination list vouchers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voucher"
                ],
                "summary": "list vouchers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Voucher"
                        }
                    }
                }
            }
        },
        "/watch_files": {
            "get": {
                "description": "pagination list watch files",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watch File"
                ],
                "summary": "list watch files",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.WatchFile"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.UploadFile": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "index_name": {
                    "type": "string"
                },
                "modify_at": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "rel_path": {
                    "type": "string"
                },
                "usable": {
                    "type": "boolean"
                }
            }
        },
        "model.Voucher": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "node": {
                    "type": "string"
                },
                "usable": {
                    "type": "boolean"
                },
                "voucher": {
                    "type": "string"
                }
            }
        },
        "model.WatchFile": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "index_ext": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
